puts "THE SIMULATION OF UART COMMAND HANDLER IS STARTING..."


# SOURCE DIRECTORIES PARAMETER
set TESTBENCH_DIRECTORIES TESTBENCH
set UART_COMMAND_HANDLER_DIRECTORIES ../../../HDL/COMMUNICATION_AND_CONTROL/UART_COMMAND_HANDLER
set INCLUDE_FILES_DIRECTORIES ../../../HDL/PARAMETER

source -notrace file.tcl

source -notrace sim.tcl


