puts "THE SIMULATION OF UART IS STARTING..."


# SOURCE DIRECTORIES PARAMETER
set TESTBENCH_DIRECTORIES TESTBENCH
set UART_DIRECTORIES ../../../HDL/COMMUNICATION_AND_CONTROL/UART
set HELPER_DIRECTORIES ../../../HDL/HELPER_MODULE/BUFFER
set INCLUDE_FILES_DIRECTORIES ../../../HDL/PARAMETER

source -notrace file.tcl

source -notrace sim.tcl


