set_property PACKAGE_PIN W5 [get_ports clk_ref]						
set_property IOSTANDARD LVCMOS33 [get_ports clk_ref]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk_ref]
set_property PACKAGE_PIN U18 [get_ports rst]						
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN B18 [get_ports cac_uart_rx]						
set_property IOSTANDARD LVCMOS33 [get_ports cac_uart_rx]
set_property PACKAGE_PIN A18 [get_ports cac_uart_tx]						
set_property IOSTANDARD LVCMOS33 [get_ports cac_uart_tx]
