puts "THE SIMULATION OF SPI IS STARTING..."


# SOURCE DIRECTORIES PARAMETER
set TESTBENCH_DIRECTORIES TESTBENCH
set SPI_DIRECTORIES ../../../../HDL/COMMUNICATION_AND_CONTROL/BMP280_SENSOR_DRIVER/SPI
set INCLUDE_FILES_DIRECTORIES ../../../../HDL/PARAMETER

source -notrace file.tcl

source -notrace sim.tcl


