puts "THE SIMULATION OF CLOCK MANAGEMENT IS STARTING..."


# SOURCE DIRECTORIES PARAMETER
set TESTBENCH_DIRECTORIES TESTBENCH
set CLOCK_MANAGEMENT_DIRECTORIES ../../HDL/CLOCK_MANAGEMENT
set INCLUDE_FILES_DIRECTORIES ../../HDL/PARAMETER

source -notrace file.tcl

source -notrace sim.tcl


