puts "THE SIMULATION OF SPI IS STARTING..."


# SOURCE DIRECTORIES PARAMETER
set TESTBENCH_DIRECTORIES TESTBENCH
set SPI_COMMAND_HANDLER_DIRECTORIES ../../../../HDL/COMMUNICATION_AND_CONTROL/SPI
set INCLUDE_FILES_DIRECTORIES ../../../../HDL/PARAMETER

source -notrace file.tcl

source -notrace sim.tcl


