puts "THE SIMULATION OF SETTINGS IS STARTING..."


# SOURCE DIRECTORIES PARAMETER
set TESTBENCH_DIRECTORIES TESTBENCH
set SETTINGS_DIRECTORIES ../../../HDL/COMMUNICATION_AND_CONTROL/SETTINGS
set INCLUDE_FILES_DIRECTORIES ../../../HDL/PARAMETER

source -notrace file.tcl

source -notrace sim.tcl


